### ISSUE TITLE
Problems when using the controls in Ion Tabs

### ISSUE THREAD

**Issue by dextroart** [aquint/ion-alpha-scroll#1]
This is an AWESOME looking control!!  Thanks for the time in getting this together. 

It appears there is an issue when including this inside an ion-tab control.  It appears that it is replicating the tabs.  Screen shots below that probably tell more than a textual description.

The code
![image](https://cloud.githubusercontent.com/assets/1761873/7578986/7695615a-f822-11e4-9ceb-bc032e9a6fbb.png)

What it looks like with this commented out:
![image](https://cloud.githubusercontent.com/assets/1761873/7578992/a3d4c28c-f822-11e4-9f07-1a3cedc7cd60.png)

What it looks like with the addition of this code.   Note that the second and third tabs seem to have multiplied once per each item in the list.   More items in the list = more tabs. 
![image](https://cloud.githubusercontent.com/assets/1761873/7579011/daca8614-f822-11e4-9c23-4d92bb0fb795.png)

**Comment by dextroart** [comment]
Hmmm.   Discovered this isn't an issue with this control at all, but more of an issue with PEBCAK!    You can see the error in the code I posted above.   The </ion-item> tag should have been changed to </div>. 

AACKKK!!  Thanks for the great control.

**Comment by aquint** [comment]
Haha yes, I believe the issue was with the closing </ion-item> tag. Thank you for the feedback nonetheless and glad you enjoy it!
