### ISSUE TITLE
Jump to section not working

### ISSUE THREAD

**Issue by MrPro100** [aquint/ion-alpha-scroll#7]
When I click on the button index letters, nothing happensю

In Google console warning: Delegate for handle "alphaScroll" could not find a corresponding element with delegate-handle="alphaScroll"! anchorScroll() was not called!
Possible cause: If you are calling anchorScroll() immediately, and your element with delegate-handle="alphaScroll" is a child of your controller, then your element may not be compiled yet. Put a $timeout around your call to anchorScroll() and try again.

Version ionic and Cordova:

Ionic: 1.6.4
Cordova: 5.1.1

**Comment by MrPro100** [comment]
I resolve this - delegate-handle is array

**Comment by officert** [comment]
@MrPro100 how did you solve this issue? I'm running into the same thing.
